// src/modules/users/user.service.ts
import { auth } from "../../lib/auth.js";
import { prisma } from "../../db/client.js";

export async function createUser(
  instId: string,
  phoneNumber: string,
  role: string,
  email?: string
) {
  const userRole = await prisma.roles.findUnique({ where: { name: role } });
  if (!userRole) throw new Error(`Unknown role: ${role}`);

  const result = await auth.api.signUpEmail({
    body: {
      email: email ?? `${phoneNumber}@placeholder.school-erp.local`,
      password: crypto.randomUUID(), // placeholder — actual temp password generated by password.util
      name: phoneNumber,
      phoneNumber: phoneNumber,
      inst_id: instId,
      role_id: userRole.id,
      is_temp_password: true,
      is_active: true,
      is_archived: false,
    },
  });

  return { user: result.user };
}
